# language: haskell

# See http://www.reddit.com/r/haskell/comments/1os3f6/how_to_use_travisci_with_multiple_ghc_versions/

env:
 - GHCVER=7.0.4
 - GHCVER=7.4.2
 - GHCVER=7.6.3
 - GHCVER=7.8.4
 - GHCVER=7.10.3
 - GHCVER=8.0.2
 - GHCVER=8.2.2
 - GHCVER=8.4.3

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install alex-3.1.7 happy-1.19.5 cabal-install-2.2 ghc-$GHCVER
 - export PATH=/opt/cabal/bin:/opt/ghc/$GHCVER/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH

install:
 - cabal-2.2 update
 - cabal-2.2 install --only-dependencies --enable-tests;

script:
 - cabal-2.2 configure --enable-tests
 - cabal-2.2 build
 - cabal-2.2 test
 - cabal-2.2 check
 - cabal-2.2 haddock
 - cabal-2.2 sdist
